using System.Xml.Serialization;

namespace NestPayDotNet.NestPay.Models
{
    /// <summary>
    /// Represents the extra information returned in the response from the NestPay API after processing a transaction.
    /// </summary>
    [XmlRoot("Extra")]
    public class TransactionResponseExtra
    {
        /// <summary>
        /// The transaction date and time in the format "yyyyMMdd HH:mm:ss".
        /// </summary>
        [XmlElement("TRXDATE")]
        public string TrxDate { get; set; }

        /// <summary>
        /// The transaction identifier assigned by the payment gateway.
        /// </summary>
        [XmlElement("EXTENDED_ERROR_CODE")]
        public string ExtendedErrorCode { get; set; }

        /// <summary>
        /// The transaction identifier assigned by the payment gateway.
        /// </summary>
        [XmlElement("TRACEID")]
        public string TraceId { get; set; }

        /// <summary>
        /// End Error code, generated by adding numeric portion of Extra.ERRORCODE to ProcReturnCode. Numeric, max 20 digits
        /// </summary>
        [XmlElement("NUMCODE")]
        public string NumCode { get; set; }

        /// <summary>
        /// Error code (if any) returned by the payment gateway. Alphanumeric, max 16 chars
        /// </summary>
        [XmlElement("ERRORCODE")]
        public string ErrorCode { get; set; }
    }
}
